(function(){MOGU.qzone_bind=function(b){if(MOGUPROFILE.userid!=""){var c=$("#sina_weibo_follow").size(),a=window.location.href;b==3&&c==0&&a.indexOf("is_qzone")<0&&a.indexOf("/elegant")<0&&a.indexOf("/note")<0&&$.ajax({url:"/collect/ispopqqnewbind",type:"POST",timeout:6E4,data:{},dataType:"json",success:function(a){if(a==null)alert(MGLANG.msgTimeout);else{var b=a.status.msg;a.status.code!=1001&&alert(b)}}})}}})(jQuery);
(function(a){MOGU.Image_Lazy_Load=function(g){if(g!==""){var c=[],h="",e=0,f=!1,i=null,e=document.body.clientHeight&&document.documentElement.clientHeight?document.body.clientHeight<document.documentElement.clientHeight?document.body.clientHeight:document.documentElement.clientHeight:document.body.clientHeight>document.documentElement.clientHeight?document.body.clientHeight:document.documentElement.clientHeight,j=e*2,k=function(){for(var b=g.split(","),d=0;d<b.length;d++){var c=b[d];c.slice(-4)!=
" img"&&(b[d]=a.trim(c)+" img")}h=b.join(",")},l=function(){a(h).each(function(){(a(this).attr("src")===void 0||a(this).attr("src")===""||a(this).attr("src").indexOf("loading")!==-1)&&(a(this).attr("d-src")!==""||a(this).attr("d-src")!==void 0)&&c.push(this)})};(function(){k();l();c.length!==0&&(i=setInterval(function(){c.length===0&&clearInterval(i);if(!f){f=!0;for(var b=0;b<c.length;b++){var d=a(c[b]);d.offset().top<a(window).scrollTop()+j+e&&d.offset().top>a(window).scrollTop()-j&&(d.attr("src",
d.attr("d-src")),c.splice(b,1),b--)}f=!1}},100))})()}}})(jQuery);
(function(c){MGPLUGIN.Photo_Slide=function(){var f=arguments.length;if(!(f!=1&&f<4)){var a={},a=f>=4?{listID:arguments[0],listBtnID:arguments[1],feedClassName:arguments[2],feedWidth:arguments[3],feedBoxClass:arguments[4]}:arguments[0];if(!MGTOOL.empty(a)&&!MGTOOL.empty(a.listID)&&!MGTOOL.empty(a.listBtnID)&&!MGTOOL.empty(a.feedClassName)&&!MGTOOL.empty(a.feedWidth)&&c("#"+a.listID).size()!=0){var e=0,d=1,j=null,h=[],g=null,g=MGTOOL.empty(a.feedBoxClass)?c("#"+a.listID+" ul"):c("#"+a.listID+" ."+a.feedBoxClass),
k=function(){c("#"+a.listBtnID+" li").removeClass("c");c("#"+a.listBtnID+" li").eq(d%e).addClass("c");g.animate({left:"-"+a.feedWidth*2+"px"},150,i());d++;d>e&&(d=1)},f=function(){c("#"+a.listBtnID+" li").each(function(b){c(this).click(function(){clearInterval(j);c("#"+a.listBtnID+" li").removeClass("c");c(this).addClass("c");b+1>d?(i(b+1),g.animate({left:"-"+a.feedWidth*2+"px"},150)):b+1<d&&(i(null,b+1),g.animate({left:"0px"},150));d=b+1;j=setInterval(k,5E3)})})},i=function(b,c){if(b==null||b==void 0)b=
d%e+1;if(c==null||b==void 0)c=d-1==0?e:d-1;g.html("").append(h[c-1].clone()).append(h[d-1].clone()).append(h[b-1].clone()).css({left:"-"+a.feedWidth+"px"})},l=function(){for(var b=c("#"+a.listID+" ."+a.feedClassName).clone(),d=0;d<b.length;d++)h[d]=b.eq(d)},m=function(){if(e>1)for(var b=0;b<e-1;b++)c("#"+a.listBtnID+">ul").append("<li></li>")},e=c("#"+a.listID+" ."+a.feedClassName).size();e>0&&(m(),e>1&&(l(),f(),i()));e>1&&(j=setInterval(k,5E3))}}}})(jQuery);
(function(a){function m(q){var k=a(this),e=null,i=[],g=null,d=a.extend({rowSelector:"> li",submenuSelector:"*",submenuDirection:"right",tolerance:75,enter:a.noop,exit:a.noop,activate:a.noop,deactivate:a.noop,exitMenu:a.noop},q),n=function(c){i.push({x:c.pageX,y:c.pageY});i.length>3&&i.shift()},o=function(c){c!=e&&(e&&d.deactivate(e),d.activate(c),e=c)},p=function(c){var b=m();b?g=setTimeout(function(){p(c)},b):o(c)},m=function(){function c(a,b){return(b.y-a.y)/(b.x-a.x)}var b=k.offset(),a={x:b.left,
y:b.top-d.tolerance},e={x:b.left+k.outerWidth(),y:a.y},g={x:b.left,y:b.top+k.outerHeight()+d.tolerance},l={x:b.left+k.outerWidth(),y:g.y},j=i[i.length-1],f=i[0];if(!j)return 0;f||(f=j);if(f.x<b.left||f.x>l.x||f.y<b.top||f.y>l.y)return 0;var h=e,b=l;d.submenuDirection=="left"?(h=g,b=a):d.submenuDirection=="below"?(h=l,b=g):d.submenuDirection=="above"&&(h=a,b=e);a=c(j,h);j=c(j,b);h=c(f,h);f=c(f,b);if(a<h&&j>f)return 300;return 0};k.mouseleave(function(){g&&clearTimeout(g);d.exitMenu(this)&&(e&&d.deactivate(e),
e=null)}).find(d.rowSelector).mouseenter(function(){a(document).mousemove(n);g&&clearTimeout(g);d.enter(this);p(this)}).mouseleave(function(){a(document).unbind("mousemove");d.exit(this)}).click(function(){o(this)});a(document).mousemove(n)}a.fn.menuAim=function(a){this.each(function(){m.call(this,a)});return this}})(jQuery);
(function(a){function g(a){this._option=a||{}}(function(){var c=a(".index_cate_wrap"),b=c.find(".index_cate_list");c.menuAim({activate:function(d){var d=a(d),c=d.attr("targ"),c=a("."+c);d.addClass("hover");var e=b.index(d);if(e===0||e==6)d.removeClass("btnone");else if(e==5||e==7)d.removeClass("btnone"),a(b).eq(e).append('<div class="bottombg">'),a(b).after("</div>");c.show();a("#more_cate_show_wrap").show()},deactivate:function(d){var d=a(d),f=d.attr("targ"),f=a("."+f);d.removeClass("hover");var e=
b.index(d);e===0||e===6?d.addClass("btnone"):(e==5||e==7)&&d.find(".bottombg").remove();c.find(".index_cate_list").first().addClass("btnone");f.hide();a("#more_cate_show_wrap").hide()},rowSelector:"> .index_cate_list",exitMenu:function(){return!0}})})();(function(){var c=function(b){var d=a(".banner_img_big li").size()-1,c=a(".banner_img_small li").index(a(".banner_img_small .c")),b=typeof b!="undefined"?b:c==d?0:c+1;a(".banner_img_big li").hide();a(".banner_img_big li").eq(b).show();a(".banner_img_small li").removeClass("c");
a(".banner_img_small li").eq(b).addClass("c")};a(".banner_img_small li").removeClass("c");a(".banner_img_small li").eq(0).addClass("c");startRun=setInterval(function(){c()},4E3);a(".banner_img_small li").hover(function(){var b=a(".banner_img_small li").index(a(this));c(b);clearInterval(startRun)},function(){startRun=setInterval(function(){c()},4E3)});a(".banner_img_big li").hover(function(){var b=a(".banner_img_big li").index(a(this));c(b);clearInterval(startRun)},function(){startRun=setInterval(function(){c()},
4E3)})})();(function(){var c=a(".dapei_tab_switch a");c.mouseenter(function(){c.removeClass("c");var b=a(this);b.addClass("c");a(".index_dapei_show .bd_wrap").hide();b=b.attr("tag");a(".index_dapei_show").find("."+b).show()})})();MOGU.Star_Dapei_Round=function(){var c=function(b,c){var f=function(a){var b=Math.floor(5*Math.random());return b==a?f(a):b},e=f(b),g=f(c);a(".mg_d li").not(a(".nofl")).eq(e).find("a.shade").addClass("hover");a(".hr_d li").not(a(".nofl")).eq(g).find("a.shade").addClass("hover")};
start_run=setInterval(function(){var b=a(".mg_d li").not(a(".nofl")).find("a.shade").index(a(".mg_d li a.hover")),d=a(".hr_d li").not(a(".nofl")).find("a.shade").index(a(".hr_d li a.hover"));a(".user_show_list li").find("a.shade").removeClass("hover");c(b,d)},2E3);a(".user_show_list li").hover(function(){clearInterval(start_run);a(this).parent().find("li a.shade").removeClass("hover");a(this).find("a.shade").addClass("hover");a(this).find("a.shade .t1").animate({top:"10px"},0);a(this).find("a.shade .t2").animate({top:"10px"},
0)},function(){clearTimeout(null);a(this).find("a.shade span").attr("style","");start_run=setInterval(function(){var b=a(".mg_d li").not(a(".nofl")).find("a.shade").index(a(".mg_d li a.hover")),d=a(".hr_d li").not(a(".nofl")).find("a.shade").index(a(".hr_d li a.hover"));a(".user_show_list li").find("a.shade").removeClass("hover");c(b,d)},2E3)})};MOGU.Star_Dapei_Round();g.prototype.holder=function(){var c=this._option.holderMod.find(".mx_tagv"),b=this._option.holderMod.find(".mx_defv"),d=c.attr("def-v");
c.focus(function(){var a=b.text();d==a&&b.hide()}).blur(function(){var d=c.val();a.trim(d)==""&&b.show()})};(new g({holderMod:a(".mx_placehold_pass")})).holder();(function(){a("#index_login_form").submit(function(){var c=a(this).find(".name").val(),b=a(this).find(".name").attr("def-v"),d=a(this).find(".password").val();if(c==b||d==""){var f=new MGLightBox({title:" ",lightBoxId:"login_msg_tip",scroll:!0,isBgClickClose:!1});f.init();c==b?f.fail("\u7528\u6237\u540d\u4e0d\u80fd\u4e3a\u7a7a",800):d==""&&
f.fail("\u5bc6\u7801\u4e0d\u80fd\u4e3a\u7a7a",800);return!1}})})();MGPLUGIN.Photo_Slide("look_list_box","look_tab_switch","look_list_item",282);MGPLUGIN.Photo_Slide("beauty_try_wrap","try_dot_wrap","beauty_try_item",480);MOGU.Globe_Input_Text_Hide(a(".login_content .name"));MOGU.Image_Lazy_Load&&MOGU.Image_Lazy_Load(".goodslist .good img")})(jQuery);
